linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/Work4Labs/uservice-applications
  gomnd:
    # don't include the "operation" and "assign" checks
    checks: argument,case,condition,return
  govet:
    shadow: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    # - depguard
    - dogsled
    # - dupl
    - errcheck
    # - exportloopref
    - exhaustive
    - goconst
    - godot
    - gocritic
    - gofmt
    - goimports
    # - gomnd
    - mnd
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
issues:
  fix: true
  exclude-rules:
    - path: _test\.go # disable some linters for test files
      linters:
        - gocyclo
        - gosec
        # - dupl
    - linters:
        - gosec
      text: "weak cryptographic primitive"
    - linters:
        - stylecheck
      text: "error strings should not be capitalized"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  issues-exit-code: 1
